### PR TITLE
Fixing print issue.:

### LINKED ISSUE #149: Print is  broken
**Describe the bug**
Latest module updates has cause the print functionality to break the app when used.

**To Reproduce**
1. Go to app
2. Enter address
3. Select print button

**Expected behavior**
A new tab with the print formatting should be provided to users

### PR DESCRIPTION
**Pull request by jedgar1mx**
## Changes
- Update declaration of print section  variables.

### CODE REVIEW

File: src/components/Display.js [hunk 1]
```diff
@@ -1031,21 +1031,21 @@ export default class Display extends HTMLElement {
         break;
 
       case 'print':
-        parcelData = JSON.parse(app[0].getAttribute('data-parcel-id'));
```
Comment (maxatdetroit) [inline src/components/Display.js:1034]: @jedgar1mx was the bug due to this variable being used in other `case` statements and already containing data?

If so, another good way to prevent that from happening is defining a lexical scope for each case statement where variables are defined.
